// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDo.Models;

public partial class Todo
{
    public int Id { get; set; }

    public string Description { get; set; }

    public bool Status { get; set; }
}